### PR TITLE
upgrade to version remix version 1.16.1

### PR DESCRIPTION
**Pull request by scshiv29-dev**
Upgraded the remix version along with @remix-run/react @remix-run/node @remix-run/serve and added @remix-run/cloudfare because it was the [solution](https://github.com/remix-run/remix/issues/3103) for "fs/promise" error i was getting with @remix-run/node .

/claim #15 

lmk if there are any other changes in this code base i need to make

### CODE REVIEW

**Comment by ericallam** [comment]
After pulling this PR and running `npm i` I got this error:

```
jsonhero.io $ npm i

> postinstall
> remix setup cloudflare-workers

ENOENT: no such file or directory, scandir '/Users/eric/code/APIHero/jsonhero/jsonhero.io/node_modules/@remix-run/react/magicExports'
npm ERR! code 1
npm ERR! path /Users/eric/code/APIHero/jsonhero/jsonhero.io
npm ERR! command failed
npm ERR! command sh -c -- remix setup cloudflare-workers

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eric/.npm/_logs/2023-05-24T20_37_07_915Z-debug-0.log
```

**Comment by scshiv29-dev** [comment]
@ericallam  sure will take a look

**Comment by scshiv29-dev** [comment]
@ericallam  so I checked and it is still necessary for us to use ``` remix setup cloudflare-workers" 
image

I also upgraded some packages  that I missed in my first commit and ran  ``` npm i ``` and then it is working 

also ran with postinstall script ```remix setup cloudflare``` and it is also working 
`> postinstall
> remix setup cloudflare

Successfully setup Remix for cloudflare.

up to date, audited 1469 packages in 4s

209 packages are looking for funding
  run `npm fund` for details

15 vulnerabilities (14 high, 1 critical)

To address all issues, run:
  npm audit fix
`

**Comment by ericallam** [comment]
`npm i` now works (nice one!) but I'm getting issues with tailwind when running the app locally with `npm run dev`. I think we'll need to upgrade the tailwind stuff to use the new built-in Remix support for tailwind:

https://remix.run/docs/en/1.16.0/guides/styling#tailwind-css

**Comment by scshiv29-dev** [comment]
@ericallam  even i was getting the tailwind error when i tried to deploy it  , let me take a look on how to fix it

**Comment by scshiv29-dev** [comment]
@ericallam  did you get a chance to review the PR ?

**Comment by matt-aitken** [comment]
Eric is away so I'll take this over. 

I did a fresh checkout of this branch and followed the steps in the `DEVELOPMENT.md`. I get this error when running `npm start`:

```
[0] [2] 💿 Building...
[1] [mf:err] /Users/matt/Desktop/jsonhero/dist/worker.js:5855
[1]         LANG: navigator.language + ".UTF-8",
[1]               ^
[1] 
[1] ReferenceError: navigator is not defined
[1]     at node_modules/@jspm/core/nodelibs/browser/process.js (/Users/matt/Desktop/jsonhero/node_modules/@jspm/core/nodelibs/browser/process.js:70:9)
[1]     at /Users/matt/Desktop/jsonhero/dist/worker.js:5610:59
[1]     at node_modules/esbuild-plugin-polyfill-node/polyfills/process.js (/Users/matt/Desktop/jsonhero/node_modules/esbuild-plugin-polyfill-node/polyfills/process.js:1:1)
[1]     at /Users/matt/Desktop/jsonhero/dist/worker.js:5610:59
[1]     at node_modules/@jspm/core/nodelibs/browser/buffer.js (/Users/matt/Desktop/jsonhero/node_modules/@jspm/core/nodelibs/browser/buffer.js:1:1)
[1]     at /Users/matt/Desktop/jsonhero/dist/worker.js:5610:59
[1]     at node_modules/esbuild-plugin-polyfill-node/polyfills/buffer.js (/Users/matt/Desktop/jsonhero/node_modules/esbuild-plugin-polyfill-node/polyfills/buffer.js:1:1)
[1]     at /Users/matt/Desktop/jsonhero/dist/worker.js:5610:59
[1]     at /Users/matt/Desktop/jsonhero/build/<stdin>:1:1
[1]     at /Users/matt/Desktop/jsonhero/dist/worker.js:95025:3
[1] [mf:err] Unhandled Promise Rejection: /Users/matt/Desktop/jsonhero/dist/worker.js:5855
[1]         LANG: navigator.language + ".UTF-8",
[1]               ^
[1] 
[1] ReferenceError: navigator is not defined
[1]     at node_modules/@jspm/core/nodelibs/browser/process.js (/Users/matt/Desktop/jsonhero/node_modules/@jspm/core/nodelibs/browser/process.js:70:9)
[1]     at /Users/matt/Desktop/jsonhero/dist/worker.js:5610:59
[1]     at node_modules/esbuild-plugin-polyfill-node/polyfills/process.js (/Users/matt/Desktop/jsonhero/node_modules/esbuild-plugin-polyfill-node/polyfills/process.js:1:1)
[1]     at /Users/matt/Desktop/jsonhero/dist/worker.js:5610:59
[1]     at node_modules/@jspm/core/nodelibs/browser/buffer.js (/Users/matt/Desktop/jsonhero/node_modules/@jspm/core/nodelibs/browser/buffer.js:1:1)
[1]     at /Users/matt/Desktop/jsonhero/dist/worker.js:5610:59
[1]     at node_modules/esbuild-plugin-polyfill-node/polyfills/buffer.js (/Users/matt/Desktop/jsonhero/node_modules/esbuild-plugin-polyfill-node/polyfills/buffer.js:1:1)
[1]     at /Users/matt/Desktop/jsonhero/dist/worker.js:5610:59
[1]     at /Users/matt/Desktop/jsonhero/build/<stdin>:1:1
[1]     at /Users/matt/Desktop/jsonhero/dist/worker.js:95025:3
```

Try a fresh checkout, or delete all of the build folders. Let me know if you can't reproduce after doing that.

**Comment by scshiv29-dev** [comment]
@matt-aitken  if i delete build folder then the worker.js file throws error as during the build it is required 
image

`///worker/index.js
import { createEventHandler } from "@remix-run/cloudflare-workers";

import * as build from "../build";

addEventListener(
  "fetch",
  createEventHandler({
    build,
    getLoadContext(event) {
      return {
        waitUntil(promise) {
          return event.waitUntil(promise);
        },
      };
    },
  })
);
`

this error is new, idk what spawned this coz i was able to build the project just yesterday let me have a look at this

**Comment by scshiv29-dev** [comment]
Hey @matt-aitken  @ericallam  I redid everything spent 12 straight hour on this tried different approaches and I still ended up getting the same error and it is because of esbuild-plugin-polyfill-node [issue](https://github.com/remix-run/remix/issues/6348) in remix new version I would suggest waiting for them to fix it and them change the version for production. I have made all the necessary changes required for new versions .

**Comment by matt-aitken** [comment]
@scshiv29-dev I haven't forgotten about this. I will discuss this with @ericallam when he's back on Monday morning. 

Sorry that this has been such a nightmare and out of your control. The most likely outcome is we award you the bounty and leave this PR here until Remix fix the issue.

**Comment by scshiv29-dev** [comment]
@matt-aitken You don't have to be sorry .Once the bug gets fixed from their end I will update my pr accordingly . Thanks for updating the timeline though .

**Comment by scshiv29-dev** [comment]
hey @matt-aitken  any updates regarding this ?

**Comment by ericallam** [comment]
It looks like the issue was fixed in Remix 1.17.1: https://github.com/remix-run/remix/releases/tag/remix%401.17.1

Can you upgrade and test that it fixes the issue? Once that's done we can merge this 👍

**Comment by scshiv29-dev** [comment]
@ericallam  created a new pr #167

**Pull request closed without merging**
